-- LyricBox Genius Scraper Database Schema
-- Run this in your Supabase SQL Editor
-- Creates tables for song metadata and lyrics with section markers

-- ============================================================================
-- 1. SONGS TABLE (Master Table)
-- ============================================================================
-- Stores core song identity and metadata
-- Each song gets a unique song_id (UUID) auto-generated by Supabase

CREATE TABLE IF NOT EXISTS songs (
  song_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  track_name TEXT NOT NULL,
  artist_name TEXT NOT NULL,
  peak_position INTEGER,
  
  -- Metadata from Musixmatch/MusicBrainz (populated later)
  bpm INTEGER,
  musical_key TEXT,
  genres TEXT[],
  moods TEXT[],
  release_date DATE,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Prevent duplicate songs (same artist + track)
  UNIQUE(artist_name, track_name)
);

-- Indexes for faster querying
CREATE INDEX IF NOT EXISTS idx_songs_artist ON songs(artist_name);
CREATE INDEX IF NOT EXISTS idx_songs_track ON songs(track_name);
CREATE INDEX IF NOT EXISTS idx_songs_created ON songs(created_at);

-- ============================================================================
-- 2. SONG_LYRICS TABLE (Genius Scraper Target)
-- ============================================================================
-- Stores lyrics by section (one row per section)
-- Linked to songs table via song_id

CREATE TABLE IF NOT EXISTS song_lyrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  song_id UUID NOT NULL REFERENCES songs(song_id) ON DELETE CASCADE,
  section_name TEXT NOT NULL,  -- "Verse 1", "Chorus", "Bridge", etc.
  lyrics_text TEXT NOT NULL,   -- Actual lyrics for this section
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for faster querying
CREATE INDEX IF NOT EXISTS idx_lyrics_song_id ON song_lyrics(song_id);
CREATE INDEX IF NOT EXISTS idx_lyrics_section ON song_lyrics(section_name);

-- Full-text search on lyrics
CREATE INDEX IF NOT EXISTS idx_lyrics_text_search 
  ON song_lyrics USING gin(to_tsvector('english', lyrics_text));

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================================
-- Enable RLS for both tables

ALTER TABLE songs ENABLE ROW LEVEL SECURITY;
ALTER TABLE song_lyrics ENABLE ROW LEVEL SECURITY;

-- Public read access (anyone can read)
CREATE POLICY "Allow public read on songs"
  ON songs FOR SELECT
  TO anon
  USING (true);

CREATE POLICY "Allow public read on song_lyrics"
  ON song_lyrics FOR SELECT
  TO anon
  USING (true);

-- Service role has full access (for imports/scraping)
CREATE POLICY "Allow service role full access on songs"
  ON songs FOR ALL
  TO service_role
  USING (true);

CREATE POLICY "Allow service role full access on song_lyrics"
  ON song_lyrics FOR ALL
  TO service_role
  USING (true);

-- ============================================================================
-- HELPER FUNCTIONS
-- ============================================================================

-- Function to get all lyrics for a song (concatenated)
CREATE OR REPLACE FUNCTION get_full_lyrics(p_song_id UUID)
RETURNS TEXT AS $$
BEGIN
  RETURN (
    SELECT string_agg(
      '[' || section_name || ']' || E'\n' || lyrics_text, 
      E'\n\n' 
      ORDER BY created_at
    )
    FROM song_lyrics
    WHERE song_id = p_song_id
  );
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- USAGE EXAMPLES
-- ============================================================================

-- Example 1: Insert a new song
-- INSERT INTO songs (track_name, artist_name, peak_position)
-- VALUES ('Someone You Loved', 'Lewis Capaldi', 1);

-- Example 2: Get the song_id for a song
-- SELECT song_id FROM songs 
-- WHERE artist_name = 'Lewis Capaldi' AND track_name = 'Someone You Loved';

-- Example 3: Insert lyrics sections
-- INSERT INTO song_lyrics (song_id, section_name, lyrics_text)
-- VALUES 
--   ('your-song-id-here', 'Verse 1', 'I''m going under...'),
--   ('your-song-id-here', 'Chorus', 'I need somebody...');

-- Example 4: Get all lyrics for a song
-- SELECT section_name, lyrics_text 
-- FROM song_lyrics 
-- WHERE song_id = 'your-song-id-here'
-- ORDER BY created_at;

-- Example 5: Get full lyrics concatenated
-- SELECT get_full_lyrics('your-song-id-here');

-- ============================================================================
-- NOTES
-- ============================================================================
-- 1. song_id is auto-generated UUID - DO NOT manually set it
-- 2. UNIQUE constraint on (artist_name, track_name) prevents duplicates
-- 3. ON DELETE CASCADE means deleting a song deletes all its lyrics
-- 4. Use service_role key for scraper operations (not anon key)
-- 5. Full-text search enabled on lyrics_text for fast lyric searches

